---
title: "miniproject1"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
kidz_bop_raw <- read_csv("~/SDS264_F26/projects/KB_censored-lyrics.csv")

kidz_bop <- kidz_bop_raw |>
  select(ogArtist, songName, badword, count, category, year, ogLyric, kbLyric) |>
```


```{r}
kidz_bop |> # number/proportion of verses that are cut entirely rather than reworded (by category)
  mutate(cut_line = if_else(kbLyric == "cuts verse", TRUE, FALSE)) |>
  group_by(year, category) |>
  summarize(n = n(),
            num_cut = sum(cut_line),
            prop_cut = mean(cut_line)) |>
  arrange(year) |>
  ggplot(aes(x = year, y = prop_cut, color = category)) +
    geom_point() +
    geom_smooth(se = FALSE) +
    facet_wrap(~category)
```

```{r}
top_artists <- kidz_bop |>
  mutate(ogArtist = str_replace_all(ogArtist, ", | & ", "|")) |>
  separate_rows(ogArtist, sep = "\\|") |>
  count(ogArtist) |>
  slice_max(order_by = n, n = 10)

kidz_bop |> # artist x axis
  mutate(ogArtist = str_replace_all(ogArtist, ", | & ", "|")) |>
  separate_rows(ogArtist, sep = "\\|") |>
  filter(ogArtist %in% top_artists$ogArtist) |>
  ggplot(aes(x = ogArtist, fill = ogArtist)) +
    geom_bar() +
    facet_wrap(~category) +
    labs(
      x = "",
      y = "# of Censored Lines",
      fill = "Artist",
      title = "Number of "
    ) +
    theme(axis.text.x = element_blank())

kidz_bop |> # category x axis
  mutate(ogArtist = str_replace_all(ogArtist, ", | & ", "|")) |>
  separate_rows(ogArtist, sep = "\\|") |>
  filter(ogArtist %in% top_artists$ogArtist) |>
  ggplot(aes(x = category, fill = ogArtist)) +
    geom_bar() +
    labs(
      x = "Category",
      y = "# of Censored Lines",
      fill = "Artist",
      title = "Number of Censored Lines by Category and Artist"
    )
```

```{r}
temp_censored_songz <- kidz_bop |>
  mutate(ogArtist = str_replace_all(ogArtist, ", | & ", "|")) |>
  separate_rows(ogArtist, sep = "\\|") |>
  group_by(ogArtist, songName) |>
  summarize(lines_censored = n())

censored_songz <- temp_censored_songz |>
  group_by(ogArtist) |>
  summarize(mean_lines_censored = mean(lines_censored)) |>
  arrange(mean_lines_censored)

ggplot() +
  geom_line(data = censored_songz, mapping = aes(x = fct_reorder(ogArtist, mean_lines_censored), y = mean_lines_censored, group = 1)) +
  geom_point(data = temp_censored_songz, mapping = aes(x = ogArtist, y = lines_censored), alpha = 0.2) +
  theme(axis.text.x = element_blank()) +
  labs(
    x = "Artist (ordered by mean lines censored)",
    y = "# Lines Censored",
    title = "Lines Censored per Song",
    subtitle = "Each individual point in an artist's column represents a song by that artist"
  )
```

```{r}
eval: FALSE
test_bop <- kidz_bop |>
  mutate(cut_line = if_else(kbLyric == "cuts verse", TRUE, FALSE)) |>
  filter(cut_line == FALSE) |>
  mutate(remains_same = ,
         index = ) |>
  str_sub(remains_same, 1, i)
         #replaced = 
         #replacement = )
```